language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Fd1RDjPpKk5De1AmozM469kN+LYa5vBtqUFUPYuN7T0GBHqr3PHGAnvvszDYZG0nI3QFlVuWwjGzniq9WOz87KoqOYxqyr4DwNGvPL5ru6nd8/gijIUVouuAMRR8+yqJsykYlRcGm445o3fr60eIIEQk0DUL3djtbo7gyfGlQv1riDj9XdiFKIjXoA9F8wvhOy8rID9bJDQBsKMm8AaUjx0/5D9/xuE0PlbXgncunnxrv8FsIesrZQMVnXFN36smy1aItpe2F+Maa1jcrPz9KKk3XSmgIs8pe06RmbDpeY4H6r/NRWCwEHsuL920ekpCdi7IVp0/JFH7bwgFzpekS10gC0L/nU4yJQaYhHzROnswtVgfs5LS9c7bHtbRtaYdq38aXl3jYVlVlasY/C/IywUkK2WEdcwFTlbzgP7nqLNFdXYTHXEvWcHXYbxOP2PrClLqtz4ZnW6cjaKll7xLl4KgHFE+2HwDQYMHJFY3KT2Dqbm/O1JDqIXQkv5x8fBtuMDTBArJGNr0ZOAqQ0BjcHYbUqqyJeGMtNmp/FnLue3WELDXZebTU/i0hJ6awYgkJbkyS4Li8DTguvWdpmpxcfjdbMzNRFmTN5v0WiXVDg6RR9nKnJquCynz1X/fDF0dGGeWzUEdTTIJbeOxb6QxWP27nCHm2MoWU0URXA3uZEU=
